// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apolsh/yapr-url-shortener/internal/app/service (interfaces: URLShortenerService)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/apolsh/yapr-url-shortener/internal/app/repository/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockURLShortenerService is a mock of URLShortenerService interface.
type MockURLShortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockURLShortenerServiceMockRecorder
}

// MockURLShortenerServiceMockRecorder is the mock recorder for MockURLShortenerService.
type MockURLShortenerServiceMockRecorder struct {
	mock *MockURLShortenerService
}

// NewMockURLShortenerService creates a new mock instance.
func NewMockURLShortenerService(ctrl *gomock.Controller) *MockURLShortenerService {
	mock := &MockURLShortenerService{ctrl: ctrl}
	mock.recorder = &MockURLShortenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLShortenerService) EXPECT() *MockURLShortenerServiceMockRecorder {
	return m.recorder
}

// AddNewURL mocks base method.
func (m *MockURLShortenerService) AddNewURL(arg0 entity.ShortenedURLInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewURL indicates an expected call of AddNewURL.
func (mr *MockURLShortenerServiceMockRecorder) AddNewURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewURL", reflect.TypeOf((*MockURLShortenerService)(nil).AddNewURL), arg0)
}

// GetURLByID mocks base method.
func (m *MockURLShortenerService) GetURLByID(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByID indicates an expected call of GetURLByID.
func (mr *MockURLShortenerServiceMockRecorder) GetURLByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByID", reflect.TypeOf((*MockURLShortenerService)(nil).GetURLByID), arg0)
}

// GetURLsByOwnerID mocks base method.
func (m *MockURLShortenerService) GetURLsByOwnerID(arg0 string) ([]entity.ShortenedURLInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLsByOwnerID", arg0)
	ret0, _ := ret[0].([]entity.ShortenedURLInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLsByOwnerID indicates an expected call of GetURLsByOwnerID.
func (mr *MockURLShortenerServiceMockRecorder) GetURLsByOwnerID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLsByOwnerID", reflect.TypeOf((*MockURLShortenerService)(nil).GetURLsByOwnerID), arg0)
}
